version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

  backend:
    build:
      context: './backend'
    env_file:
      - .env
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - db

  frontend:
    build:
      context: './frontend'
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend