version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - net


  backend:
    build:
      context: './backend'
    env_file:
      - .env
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - db
    networks:
      - net

  frontend:
    build:
      context: './frontend'
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      net:
        ipv4_address: ${IP}

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16