// Code generated by protoc-gen-go. DO NOT EDIT.
// source: developers.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_developers_4b771fa910398f13, []int{0}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_developers_4b771fa910398f13, []int{1}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_developers_4b771fa910398f13, []int{2}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UsernameRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsernameRequest) Reset()         { *m = UsernameRequest{} }
func (m *UsernameRequest) String() string { return proto.CompactTextString(m) }
func (*UsernameRequest) ProtoMessage()    {}
func (*UsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_developers_4b771fa910398f13, []int{3}
}
func (m *UsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsernameRequest.Unmarshal(m, b)
}
func (m *UsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsernameRequest.Marshal(b, m, deterministic)
}
func (dst *UsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsernameRequest.Merge(dst, src)
}
func (m *UsernameRequest) XXX_Size() int {
	return xxx_messageInfo_UsernameRequest.Size(m)
}
func (m *UsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsernameRequest proto.InternalMessageInfo

func (m *UsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Developer struct {
	Username             string        `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            string        `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string        `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Speciality           string        `protobuf:"bytes,5,opt,name=speciality,proto3" json:"speciality,omitempty"`
	Timezone             string        `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Introduction         string        `protobuf:"bytes,7,opt,name=introduction,proto3" json:"introduction,omitempty"`
	City                 string        `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	Languages            string        `protobuf:"bytes,10,opt,name=languages,proto3" json:"languages,omitempty"`
	Links                []*Link       `protobuf:"bytes,11,rep,name=links,proto3" json:"links,omitempty"`
	Projects             []*Project    `protobuf:"bytes,12,rep,name=projects,proto3" json:"projects,omitempty"`
	SkillGroups          []*SkillGroup `protobuf:"bytes,13,rep,name=skill_groups,json=skillGroups,proto3" json:"skill_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Developer) Reset()         { *m = Developer{} }
func (m *Developer) String() string { return proto.CompactTextString(m) }
func (*Developer) ProtoMessage()    {}
func (*Developer) Descriptor() ([]byte, []int) {
	return fileDescriptor_developers_4b771fa910398f13, []int{4}
}
func (m *Developer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Developer.Unmarshal(m, b)
}
func (m *Developer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Developer.Marshal(b, m, deterministic)
}
func (dst *Developer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Developer.Merge(dst, src)
}
func (m *Developer) XXX_Size() int {
	return xxx_messageInfo_Developer.Size(m)
}
func (m *Developer) XXX_DiscardUnknown() {
	xxx_messageInfo_Developer.DiscardUnknown(m)
}

var xxx_messageInfo_Developer proto.InternalMessageInfo

func (m *Developer) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Developer) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Developer) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Developer) GetSpeciality() string {
	if m != nil {
		return m.Speciality
	}
	return ""
}

func (m *Developer) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *Developer) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *Developer) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Developer) GetLanguages() string {
	if m != nil {
		return m.Languages
	}
	return ""
}

func (m *Developer) GetLinks() []*Link {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *Developer) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

func (m *Developer) GetSkillGroups() []*SkillGroup {
	if m != nil {
		return m.SkillGroups
	}
	return nil
}

type Link struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Link) Reset()         { *m = Link{} }
func (m *Link) String() string { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()    {}
func (*Link) Descriptor() ([]byte, []int) {
	return fileDescriptor_developers_4b771fa910398f13, []int{5}
}
func (m *Link) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link.Unmarshal(m, b)
}
func (m *Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link.Marshal(b, m, deterministic)
}
func (dst *Link) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link.Merge(dst, src)
}
func (m *Link) XXX_Size() int {
	return xxx_messageInfo_Link.Size(m)
}
func (m *Link) XXX_DiscardUnknown() {
	xxx_messageInfo_Link.DiscardUnknown(m)
}

var xxx_messageInfo_Link proto.InternalMessageInfo

func (m *Link) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Link) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Project struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Link                 string   `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Stack                string   `protobuf:"bytes,3,opt,name=stack,proto3" json:"stack,omitempty"`
	Scope                string   `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_developers_4b771fa910398f13, []int{6}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (dst *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(dst, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Project) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Project) GetStack() string {
	if m != nil {
		return m.Stack
	}
	return ""
}

func (m *Project) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

type SkillGroup struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Skills               []*Skill `protobuf:"bytes,2,rep,name=skills,proto3" json:"skills,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkillGroup) Reset()         { *m = SkillGroup{} }
func (m *SkillGroup) String() string { return proto.CompactTextString(m) }
func (*SkillGroup) ProtoMessage()    {}
func (*SkillGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_developers_4b771fa910398f13, []int{7}
}
func (m *SkillGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillGroup.Unmarshal(m, b)
}
func (m *SkillGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillGroup.Marshal(b, m, deterministic)
}
func (dst *SkillGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillGroup.Merge(dst, src)
}
func (m *SkillGroup) XXX_Size() int {
	return xxx_messageInfo_SkillGroup.Size(m)
}
func (m *SkillGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillGroup.DiscardUnknown(m)
}

var xxx_messageInfo_SkillGroup proto.InternalMessageInfo

func (m *SkillGroup) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SkillGroup) GetSkills() []*Skill {
	if m != nil {
		return m.Skills
	}
	return nil
}

type Skill struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Experience           uint32   `protobuf:"varint,2,opt,name=experience,proto3" json:"experience,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Skill) Reset()         { *m = Skill{} }
func (m *Skill) String() string { return proto.CompactTextString(m) }
func (*Skill) ProtoMessage()    {}
func (*Skill) Descriptor() ([]byte, []int) {
	return fileDescriptor_developers_4b771fa910398f13, []int{8}
}
func (m *Skill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skill.Unmarshal(m, b)
}
func (m *Skill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skill.Marshal(b, m, deterministic)
}
func (dst *Skill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skill.Merge(dst, src)
}
func (m *Skill) XXX_Size() int {
	return xxx_messageInfo_Skill.Size(m)
}
func (m *Skill) XXX_DiscardUnknown() {
	xxx_messageInfo_Skill.DiscardUnknown(m)
}

var xxx_messageInfo_Skill proto.InternalMessageInfo

func (m *Skill) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Skill) GetExperience() uint32 {
	if m != nil {
		return m.Experience
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "proto.LoginRequest")
	proto.RegisterType((*RegisterRequest)(nil), "proto.RegisterRequest")
	proto.RegisterType((*Token)(nil), "proto.Token")
	proto.RegisterType((*UsernameRequest)(nil), "proto.UsernameRequest")
	proto.RegisterType((*Developer)(nil), "proto.Developer")
	proto.RegisterType((*Link)(nil), "proto.Link")
	proto.RegisterType((*Project)(nil), "proto.Project")
	proto.RegisterType((*SkillGroup)(nil), "proto.SkillGroup")
	proto.RegisterType((*Skill)(nil), "proto.Skill")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeveloperServiceClient is the client API for DeveloperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeveloperServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Token, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*Token, error)
	Get(ctx context.Context, in *UsernameRequest, opts ...grpc.CallOption) (*Developer, error)
	Update(ctx context.Context, in *Developer, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *UsernameRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type developerServiceClient struct {
	cc *grpc.ClientConn
}

func NewDeveloperServiceClient(cc *grpc.ClientConn) DeveloperServiceClient {
	return &developerServiceClient{cc}
}

func (c *developerServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/proto.DeveloperService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/proto.DeveloperService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) Get(ctx context.Context, in *UsernameRequest, opts ...grpc.CallOption) (*Developer, error) {
	out := new(Developer)
	err := c.cc.Invoke(ctx, "/proto.DeveloperService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) Update(ctx context.Context, in *Developer, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.DeveloperService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) Delete(ctx context.Context, in *UsernameRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.DeveloperService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeveloperServiceServer is the server API for DeveloperService service.
type DeveloperServiceServer interface {
	Login(context.Context, *LoginRequest) (*Token, error)
	Register(context.Context, *RegisterRequest) (*Token, error)
	Get(context.Context, *UsernameRequest) (*Developer, error)
	Update(context.Context, *Developer) (*empty.Empty, error)
	Delete(context.Context, *UsernameRequest) (*empty.Empty, error)
}

func RegisterDeveloperServiceServer(s *grpc.Server, srv DeveloperServiceServer) {
	s.RegisterService(&_DeveloperService_serviceDesc, srv)
}

func _DeveloperService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DeveloperService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DeveloperService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DeveloperService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).Get(ctx, req.(*UsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Developer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DeveloperService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).Update(ctx, req.(*Developer))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DeveloperService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).Delete(ctx, req.(*UsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeveloperService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DeveloperService",
	HandlerType: (*DeveloperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _DeveloperService_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _DeveloperService_Register_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DeveloperService_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DeveloperService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DeveloperService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "developers.proto",
}

func init() { proto.RegisterFile("developers.proto", fileDescriptor_developers_4b771fa910398f13) }

var fileDescriptor_developers_4b771fa910398f13 = []byte{
	// 642 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0x56, 0x0e, 0x4e, 0x93, 0x49, 0xfa, 0x27, 0xff, 0x52, 0x2a, 0xcb, 0x3d, 0x50, 0x56, 0x20,
	0x55, 0x95, 0x48, 0xa4, 0xc2, 0x15, 0x12, 0x17, 0x48, 0x85, 0x72, 0x51, 0x55, 0xc8, 0xa5, 0x17,
	0x48, 0x48, 0x95, 0xeb, 0x4c, 0xad, 0x25, 0xae, 0xd7, 0xec, 0xae, 0x0b, 0x05, 0x71, 0x83, 0xc4,
	0x13, 0xf0, 0x24, 0x3c, 0x0b, 0xaf, 0xc0, 0x53, 0x70, 0x85, 0xf6, 0x60, 0x37, 0x18, 0xa5, 0x2a,
	0x57, 0xd9, 0x99, 0x6f, 0xe6, 0x9b, 0x6f, 0x32, 0x9e, 0x81, 0xd1, 0x14, 0x2f, 0x30, 0xe5, 0x39,
	0x0a, 0x39, 0xce, 0x05, 0x57, 0x9c, 0x78, 0xe6, 0x27, 0x58, 0x4b, 0x38, 0x4f, 0x52, 0x9c, 0x18,
	0xeb, 0xb4, 0x38, 0x9b, 0xe0, 0x79, 0xae, 0x2e, 0x6d, 0x4c, 0xb0, 0xee, 0xc0, 0x28, 0x67, 0x93,
	0x28, 0xcb, 0xb8, 0x8a, 0x14, 0xe3, 0x99, 0x63, 0xa0, 0xcf, 0x61, 0x70, 0xc0, 0x13, 0x96, 0x85,
	0xf8, 0xae, 0x40, 0xa9, 0x48, 0x00, 0xdd, 0x42, 0xa2, 0xc8, 0xa2, 0x73, 0xf4, 0x1b, 0x5b, 0x8d,
	0xed, 0x5e, 0x58, 0xd9, 0x1a, 0xcb, 0x23, 0x29, 0xdf, 0x73, 0x31, 0xf5, 0x9b, 0x16, 0x2b, 0x6d,
	0xfa, 0xb5, 0x01, 0xc3, 0x10, 0x13, 0x26, 0x15, 0x8a, 0x9b, 0x70, 0x6d, 0x00, 0x9c, 0x31, 0x21,
	0xd5, 0x89, 0x41, 0x2d, 0x5b, 0xcf, 0x78, 0x0e, 0x35, 0xbc, 0x06, 0xbd, 0x34, 0x2a, 0xd1, 0x96,
	0xcd, 0xd5, 0x8e, 0xc3, 0xba, 0x8e, 0x76, 0x4d, 0xc7, 0x06, 0x78, 0xaf, 0xf8, 0x0c, 0x33, 0xb2,
	0x02, 0x9e, 0xd2, 0x0f, 0x57, 0xd9, 0x1a, 0xf4, 0x01, 0x0c, 0x8f, 0x9d, 0x84, 0x1b, 0xa8, 0xa4,
	0xbf, 0x9a, 0xd0, 0xdb, 0x2b, 0xff, 0xf4, 0x7f, 0xe8, 0xa7, 0x75, 0x6d, 0x3f, 0xed, 0x5a, 0x3f,
	0x9b, 0x00, 0x32, 0xc7, 0x98, 0x45, 0x29, 0x53, 0x97, 0xbe, 0x67, 0xd0, 0x39, 0x8f, 0xae, 0xab,
	0xd8, 0x39, 0x7e, 0xe4, 0x19, 0xfa, 0x1d, 0x9b, 0x5b, 0xda, 0x84, 0xc2, 0x80, 0x65, 0x4a, 0xf0,
	0x69, 0x11, 0xeb, 0xb1, 0xfa, 0x4b, 0x06, 0xff, 0xc3, 0x47, 0x08, 0xb4, 0x63, 0xcd, 0xdc, 0x35,
	0x98, 0x79, 0x93, 0x75, 0x2d, 0x28, 0x4b, 0x8a, 0x28, 0x41, 0xe9, 0x83, 0x95, 0x5b, 0x39, 0xc8,
	0x5d, 0xf0, 0x52, 0x96, 0xcd, 0xa4, 0xdf, 0xdf, 0x6a, 0x6d, 0xf7, 0x77, 0xfb, 0xf6, 0x63, 0x19,
	0x1f, 0xb0, 0x6c, 0x16, 0x5a, 0x84, 0xec, 0x40, 0x37, 0x17, 0xfc, 0x2d, 0xc6, 0x4a, 0xfa, 0x03,
	0x13, 0xf5, 0x9f, 0x8b, 0x7a, 0x69, 0xdd, 0x61, 0x85, 0x93, 0x47, 0x30, 0x90, 0x33, 0x96, 0xa6,
	0x27, 0x89, 0xe0, 0x45, 0x2e, 0xfd, 0x65, 0x13, 0xff, 0xbf, 0x8b, 0x3f, 0xd2, 0xd0, 0xbe, 0x46,
	0xc2, 0xbe, 0xac, 0xde, 0x92, 0x8e, 0xa1, 0xad, 0x0b, 0x9a, 0x49, 0x32, 0x95, 0x62, 0x35, 0x49,
	0x6d, 0x90, 0x11, 0xb4, 0x0a, 0x91, 0xba, 0x2f, 0x47, 0x3f, 0xe9, 0x09, 0x2c, 0xb9, 0xd2, 0x0b,
	0x52, 0x08, 0xb4, 0xb5, 0x76, 0x97, 0x63, 0xde, 0x3a, 0x52, 0xaa, 0x28, 0x9e, 0xb9, 0x91, 0x59,
	0xc3, 0x78, 0x63, 0x9e, 0x97, 0xa3, 0xb2, 0x06, 0x7d, 0x01, 0x70, 0xa5, 0x75, 0x41, 0x8d, 0x7b,
	0xd0, 0x31, 0x3d, 0x48, 0xbf, 0x69, 0x9a, 0x1c, 0xcc, 0x37, 0x19, 0x3a, 0x8c, 0x3e, 0x01, 0xcf,
	0x38, 0x16, 0x90, 0x6c, 0x02, 0xe0, 0x87, 0x1c, 0x05, 0xc3, 0x2c, 0xb6, 0xcb, 0xb1, 0x1c, 0xce,
	0x79, 0x76, 0xbf, 0xb7, 0x60, 0x54, 0x7d, 0x96, 0x47, 0x28, 0x2e, 0x58, 0x8c, 0xe4, 0x29, 0x78,
	0x66, 0x93, 0xc9, 0xad, 0x72, 0x5a, 0x73, 0x7b, 0x1d, 0x94, 0x3a, 0xcc, 0x72, 0xd0, 0xdb, 0x5f,
	0x7e, 0xfc, 0xfc, 0xd6, 0x1c, 0x52, 0x30, 0x57, 0x21, 0xd5, 0x81, 0x8f, 0x1b, 0x3b, 0xe4, 0x00,
	0xba, 0xe5, 0x0e, 0x93, 0x55, 0x97, 0x50, 0x5b, 0xea, 0x1a, 0x51, 0x60, 0x88, 0x56, 0xe8, 0xd0,
	0x10, 0x5d, 0xdd, 0x27, 0xcd, 0x76, 0x04, 0xad, 0x7d, 0x54, 0x15, 0x51, 0x6d, 0xef, 0x82, 0x91,
	0xf3, 0x57, 0x8d, 0x50, 0x6a, 0xc8, 0xd6, 0x49, 0x50, 0x23, 0x9b, 0x7c, 0x2a, 0xd7, 0xec, 0x33,
	0x79, 0x0d, 0x9d, 0xe3, 0x7c, 0x1a, 0x29, 0x24, 0x7f, 0xe5, 0x07, 0xab, 0x63, 0x7b, 0xea, 0xc6,
	0xe5, 0x1d, 0x1c, 0x3f, 0xd3, 0x77, 0x90, 0xde, 0x37, 0xbc, 0x77, 0x82, 0x6b, 0x78, 0xb5, 0xde,
	0x37, 0xd0, 0xd9, 0xc3, 0x14, 0x15, 0x2e, 0x94, 0xbc, 0xa8, 0x80, 0x13, 0xbe, 0x73, 0x4d, 0x81,
	0xd3, 0x8e, 0xc9, 0x79, 0xf8, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xa1, 0xdc, 0xaf, 0xc5, 0x05,
	0x00, 0x00,
}
